### PR TITLE
Fix type in docker exec command

### PR DESCRIPTION
**Pull request by mycarrysun**
Is this what the original implementation was supposed to be?

### CODE REVIEW

**Comment by jradtilbrook** [comment]
Hi @mycarrysun this proposed change is an invalid docker command. `docker exec` is valid, but the command in this example script is to run a new container with `docker run`.

Thanks for checking though 👍

**Comment by mycarrysun** [comment]
@jradtilbrook `exec` is not a command though. That's my point. If you copy paste that example it will give you an error. The docs are wrong.

**Comment by jradtilbrook** [comment]
Hmm, what shell are you using? And what version of docker?

If I copy, paste and run the command as it is on the master branch into a terminal: `exec docker --log-level warn run -t --rm hello-world` it works as I expect - it runs the container and because of the `exec` it moves stdin/stdout and exits the terminal after running.  
If I run the change proposed: `docker exec --log-level warn run -t --rm hello-world` I get the error:
```
unknown flag: --log-level
See 'docker exec --help'.
```
Because it is mixing 2 docker subcommands: `exec` and `run`.

Perhaps you are having issues trying to pass any arguments to the container from the `"$@"`. This is actually broken as well since the container doesn't accept any arguments nor have any interactive shell.

But having said all this, this repo is an example of how to write a plugin using hooks and bringing your own binaries to assist. It is not intended to be taken verbatim as it is not very useful to actual execute. We would accept a PR to remove the "$@" though since that is broken.

**Comment by mycarrysun** [comment]
On mac the `exec` command is exiting the terminal and that is a bit jarring. Why do we need the `exec` command on the front? I'm also getting the same error as you said (`--log-level`) but that's just because my original version of the code was wrong...it should actually be `docker --log-level warn run -t --rm hello-world` which works without errors.

**Comment by jradtilbrook** [comment]
Yeah thats correct it will work without `exec` at the front.  
[`exec`](https://man7.org/linux/man-pages/man1/exec.1p.html) replaces the shell with the process being opened (docker in this case). This has the effect of copying of input/output streams but probably more usefully in the case of a Buildkite pipeline, the docker command will then receive any signals sent to the `hello-world` script (because it replaces the process).

This will allow the docker process to listen for SIGTERM and exit gracefully. This can happen if the instance is shutdown or the pipeline is cancelled etc.

**Pull request closed without merging**
